### ISSUE TITLE
Update sanity schema to support projects pre-finance

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-sanity#55]
We need to be able to tag an off chain project as a prefinance project and attach the following info:
- price (TBC, maybe this can be pulled from stripe API instead)
- estimated issuance
- project prefinance terms
- link to purchase agreement
- projected credit delivery date
- items for "what your support will enable"
- project/class status info
- stripe payment link

Design: https://www.figma.com/file/EPSVuGURedvRfO6LxUAQZs/Pre-financing?type=design&node-id=0-1&mode=design&t=r1y3kjhtZVimeQBO-0

**Comment by blushi** [comment]
@erikalogie please could you confirm this is what we need and let us know here when we know more about the project statuses, thanks

**Comment by erikalogie** [comment]
@blushi I think that this should be ready to go, these are the project statuses: https://www.figma.com/file/EPSVuGURedvRfO6LxUAQZs/Pre-financing?type=design&node-id=456%3A24059&mode=design&t=daVy6NVXXZakJef9-1. Every status except the final one should show up as yellow.

Here are the credit class statuses: https://www.figma.com/file/EPSVuGURedvRfO6LxUAQZs/Pre-financing?type=design&node-id=456%3A24149&mode=design&t=daVy6NVXXZakJef9-1. We may need an "internal review round 2" and

**Comment by clevinson** [comment]
For now, let's have just the "Credit Class Status" and "Project Status" overviews with:
- description
- date (stored as date, but formatted as Month Year)
- color of button (Yellow or Green)

We will have a separate issue for tracking the "timeline view" of project / credit class status.

<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba7feb4396e0ab3fc34d37bfe3fca7a00efcac91/Screenshot%202024-02-12%20at%208.12.06%20AM.png" alt="Screenshot 2024-02-12 at 8.12.06 AM.png" />

**Comment by blushi** [comment]
Yeah currently, these things are backed by regen-server, we already have timestamp stored in the `post` database table and the file mimetype stored in the `upload` table.
I believe it could be nice to think about use cases where this could be useful to have that in the JSON-LD itself.
